### ISSUE TITLE
i want to excute the link every minutes 

### ISSUE THREAD

**Issue by abasakre** [techwithsam/flutter-push-notification-without-firebase#2]
i want to excute the link every minutes

**Comment by techwithsam** [comment]
The minimum time for the code to execute is 5min.

**Comment by syarifhdyt23** [comment]
In the tutorial, you added a background fetch to the project, but why isn't there on Github?

**Comment by techwithsam** [comment]
Everything in the tutorial is on github

**Comment by sumit311998** [comment]
Can it be extended to automated image push notification Or Event driven push notification

**Comment by techwithsam** [comment]
Yeah, based on what you set on your database.

**Comment by RushabhShah11700** [comment]
I want to understand the php api code can you elaborate that part??

**Comment by techwithsam** [comment]
The API connects to the database and check if there Is a status with 1, any message with status with 1, that means the message is a new message. So, the API would now communicate with the database and check if there is any status with 1, once the status s one it will return true, on return of true, API will send the true status to the application, that's after you have consumed all the API on the application, so the application will detect that it is true and, looking at the source code you will see that it when the **convert['status']  == true** is when **showNotification** is called. So that's the main purpose of the API to check if the status is true.

**Comment by RushabhShah11700** [comment]
> The API connects to the database and check if there Is a status with 1, any message with status with 1, that means the message is a new message. So, the API would now communicate with the database and check if there is any status with 1, once the status s one it will return true, on return of true, API will send the true status to the application, that's after you have consumed all the API on the application, so the application will detect that it is true and, looking at the source code you will see that it when the **convert['status'] == true** is when **showNotification** is called. So that's the main purpose of the API to check if the status is true.

Thanks man
